[package]
name = "maze-valence"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
flume = "0.11.1"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
valence = { git = "https://github.com/valence-rs/valence" }
