[server]
bind_address = "127.0.0.1:25565"
max_players = 20
connection_mode = "offline"
online_prevent_proxy_connections = false
velocity_secret = "CHANGE_ME"
login_message = "Welcome to the server!"

[generator]
wall = { mat = 16, max_y = 64, thick = 1 }
layer_map = [{ mat = 1, y = 60 }, { mat = 1, y = 68 }]
spawn_pos = [0, 64, 0]
