services:
  maze:
    build: .
    #image: maze-valence:latest
    container_name: maze-valence
    volumes:
      - ./maze.toml:/data/maze.toml:ro
    ports:
      - 25565:25565
    restart: unless-stopped
