[server]
bind_address = "0.0.0.0:25565"
max_players = 20
connection_mode = "offline"
online_prevent_proxy_connections = false
velocity_secret = "CHANGE_ME"

[world]
center_map = [{ mat = "ochre_froglight", min_y = 66, max_y = 67, radius = 1 }]
wall_map = [
    { mat = "stripped_bamboo_block", min_y = 60, max_y = 66, thick = 1 },
]
layer_map = [
    { mat = "dirt_path", y = 60 },
    { mat = "stripped_birch_wood", y = 66 },
]
spawn_pos = [7.5, 61.25, 7.5]
wall_chance = 0.25
login_message = "Welcome to the backrooms."
biome = "the_void"
