name: Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        runner: ['ubuntu-latest']
        build: ['debug', 'release']
    runs-on: '${{ matrix.runner }}'
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Get Architecture
      run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV
    - name: Build Binary
      run: |
        RELEASE_FLAG=""
        if [ "${{ matrix.build }}" = "release" ]; then
          RELEASE_FLAG="--release"
        fi
        cargo build ${RELEASE_FLAG}
    - name: Upload Artifact
      uses: forgejo/upload-artifact@v4
      with:
        name: maze-valence-${{ env.ARCH }}-${{ matrix.build }}
        path: target/${{ matrix.build }}/maze-valence
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs:
    - build

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Download Artifacts
      uses: forgejo/download-artifact@v4
      with:
        path: artifacts
        pattern: maze-valence-*
        merge-multiple: true
    - name: List Artifacts
      run: ls -lAR artifacts
    - name: Upload Release
      uses: actions/forgejo-release@v2
      with:
        direction: upload
        url: https://git.craftingcomrades.net
        release-dir: artifacts
        token: ${{ github.token }}
        tag: "nightly"
        override: true
        prerelease: true
